language: bash
services: docker

env:
  - VERSION=5 VARIANT=
  - VERSION=5 VARIANT=alpine
  - VERSION=2.4 VARIANT=
  - VERSION=2.4 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
# https://github.com/docker-library/elasticsearch/issues/98#issuecomment-254656216
  - sudo sysctl -w vm.max_map_count=262144

before_script:
  - env | sort
  - cd "$VERSION"
  - image="elasticsearch:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
