version: '2'
services:
  nginx:
    image: mritd/nginx
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
    volumes_from:
      - piwik_app
    links:
      - jekyll
      - idea
      - yum
      - gcr
      - piwik_app
    ports:
      - "80:80"
      - "443:443"
  jekyll:
    image: mritd/jekyll
    restart: always
  idea:
    image: mritd/idea
    restart: always
  yum:
    image: mritd/yum
    restart: always  
    volumes:
      - /data/repo/centos:/usr/share/nginx/html/centos
  gcr:
    image: mritd/gcr.io
    restart: always
    volumes:
      - /data/registry:/var/lib/registry
  piwik_db:
    image: mysql:5.7.17
    restart: always
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
  piwik_app:
    image: mritd/piwik:3.0.4
    restart: always
    links:
      - piwik_db
    volumes:
      - /data/piwik/config:/var/www/html/config
